### ISSUE TITLE
Remove force behaviour from  schedule

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc310/classy#17]
Currently, the `#schedule` code creates a new GradingJob instead of a new comment request. This is causing duplicate runs of autotest, which is computationally wasteful and could clog the queues.

**Comment by braxtonhall** [comment]
scheduleQueue dequeue should really trigger a comment instead of saving a comment request from the future. It's currently possible if a commit was in multiple queues processExecution will find a comment request from the schedule and post back results, even if removed from scheduleQueue.

**Comment by braxtonhall** [comment]
AutoTest should have something like `abstract handleScheduleDequeue` that gets called in `tick`

In the implemented version in GitHubAutoTest, comment request is triggered

**Comment by jyoo980** [comment]
Taking a look at this to get my bearings, I noticed that `GitHubAutoTest.schedule(..)` appends a commit request to the standard queue as opposed, to the schedule queue. Is this by design? 

I guess it would make sense if you're appending it to the standard queue for processing later, but then what's the point of having a schedule queue at all? Does the schedule queue handle requests for `#schedule` before they get appended to the standard queue?

**Comment by braxtonhall** [comment]
This is intended. The schedule queue is exclusively for requests from `#schedule`. The `schedule` method schedules a permitted commit to be processed as soon as possible. The schedule queue holds commits that are not permitted to be processed yet.

Ideally the schedule queue would not have this behaviour, as commits can be processed multiple times (once from the standard queue and once from the schedule queue).

This poor naming is the result of `#schedule` being creating on top of an existing, fully-implemented system, and `GitHubAutoTest::schedule(..)` should probably be renamed to something like `enqueue`.

**Comment by braxtonhall** [comment]
OK for now we're just gonna comment it out
Dealt with in https://github.com/ubccpsc310/classy/commit/7c1e0064761c0e6acc6f2bbbd2baf84535a493c8

**Comment by rtholmes** [comment]
Really the easiest thing to do would be to check if there's an existing `deivId|RepoId|personId` tuple already queued somewhere when scheduling and just drop it if it already exists. I didn't like this feature when it came in tbh because of this complexity :) . But you'd probably want to _remove_ the prior scheduled call and add the newest one (since a user might want to replace a schedule call for a newer commit).

**Comment by rtholmes** [comment]
One other challenge is around timeouts: For courses with concurrent deliverables you will have to think about whether a single person can take multiple queue slots simultaneous (I would argue not, since technically someone could issue 3 concurrent requests for three different deliverables that time out and block the queue for the whole class).

**Comment by braxtonhall** [comment]
I think it was complex because at the time it was written I fundamentally misunderstood how the system worked. The simplest thing at this point would to rip schedule out of all the tick and processExecution code, and have it be completely separate.
Really it should just post a comment event.

**Comment by rtholmes** [comment]
Scheduling has been removed.
