### ISSUE TITLE
[Question] Should jobs only be run if queue has space

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc310/classy#65]
https://github.com/ubccpsc310/classy/blob/1c438fc72960019968a8964bb894769e43d6d8c0/packages/autotest/src/autotest/AutoTest.ts#L137

@rtholmes 
If I'm reading this correctly, if a queue is full (i.e. hasCapacity === false), no jobs are scheduled from the queue.

Just really confused and looking for some clarification. Is this intended?

**Comment by rtholmes** [comment]
Hi @braxtonhall this is confusing because of poor naming. The next line after your selection above schedules the job to run, the hasCapacity check just allows us to have multiple runners per queue (e.g., the standard queue for 310 can execute two jobs at once I think). 

If there are not enough runners available for a queue with jobs (e.g., if `hasCapacity = false`) the job remains on the queue but is not scheduled to run.

**Comment by braxtonhall** [comment]
ah ok understood thanks
